copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_NetXApi.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Client\XClient_Socket.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_DownLoad\XEngine_DownLoad.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_NetHelp\NetHelp_APIHelp.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_LibEx\libcrypto-3.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\libssl-3.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\libcurl.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\nghttp2.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_HelpComponents\zlib1.dll" "./"